globality-corp/nodule-openapi

src/__tests__/validation.test.js, src/validation.js
During retrieve operations, we commonly pass in an args list, causing
this validation to erroneously succeed. We should be failing validation
if a required key was missing, or was supplied with a null value.
=> Fix validation for missing required arguments

src/__tests__/request.builders.test.js, src/request.js
* allow `buildParams()` if context method is `get` or `delete`
Why?
It is nice to allow params to be passed for delete.
=> Include params for delete requests

src/clients/__tests__/openapi.test.js, src/clients/openapi.js, src/testing/openapi.js
The OpenAPI client is mainly used for creating and receiving JSON data;
in the case that the server starts returning back non-JSON responses
(e.g. maintenance pages), we shouldn't be treating these as valid
responses.
This is meant to solve GLOB-27019, where we end up actually caching the maintenance pages, causing us to need to forcibly reset the cache.
Ideally, this would have been caught in axios itself, but it would appear that we're sending headers like `'application/json, text/plain, */*',`, even though the latter two don't appear to be explicitly specified anywhere.
=> Raise error on receiving non-JSON responses

src/__tests__/request.builders.test.js, src/__tests__/request.test.js, src/clients/openapi.js, src/operation.js, src/request.js
By default axios will never time out on a request, meaning clients
could wait forever waiting for a response.
This updates client configuration to respect per-service timeouts, as
well as setting a baseline timeout for all clients.
I set this to 5s just as a sample default; we use 6 seconds on the proxy level, meaning we may see this error more often than we had before.
The errors from the gateways, however, is a tad cryptic:
```
{
"data": {
"user": null
},
"errors": [
{
"message": "timeout of 1000ms exceeded",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"user"
]
}
]
}```
=> Add default timeout for requests

.bumpversion.cfg, package.json, src/__tests__/error.test.js, src/error.js
Added request headers to `OpenAPIError`. This is to better contextualize the error which clients may wish to use it.
=> add request headers to open api error

.bumpversion.cfg, package.json, src/__tests__/example.json, src/__tests__/request.test.js, src/request.js
Before:
We always passed path args `chatroom/{chatroomId}` as an param arg as well - `chatroom/{chatroomId}?chatroom_id={chatroomId}`
Now:
If an arg is passed as an path arg - don't use it as param arg at all (similar to microcosm). There are limitations here: if we do want to pass the arg. However, in this case, one can replace one of the `builders`. 
Alternative approach:
Update `buildParams` to be strict as marshmallow 3.0 and silently (or not silently) discard path args based on the swagger def. @afallou had some ideas about that.
I think it's preferable approach but would require more changes in nodule-openapi and will open the discussion about strict schema uses. I would prefer to continue in this path later.
=> Use path args only in path

.bumpversion.cfg, package.json, src/clients/__tests__/openapi.test.js, src/testing/openapi.js, src/testing/petstore.json
For better or worse, `mockResponse` mocks a http response - not the nodule-openapi response.
Sometimes, when we want to control the mock response - we're using http mock request.
So far - we've used only `params` or `data`. But now, it seems that we also the url.
This PR will allow the `mockResponse` to use an optional url field. It won't break the existing api.
=> explicit mockResponse

src/__tests__/request.builders.test.js, src/request.js
Allow to configure every app default timeout instead of using hardcoded 5000ms
Especially relevant when debugging GWs on a slow network
=> Configured timeout

.eslintrc, src/__tests__/request.builders.test.js, src/__tests__/request.test.js, src/clients/__tests__/openapi.test.js, src/clients/openapi.js, src/operation.js, src/request.js
Under times of high load, we may run into situations where a given
service fails due to some kind of transient issue (e.g. a misbehaving
service instance). In those cases, we can be proactive about retrying
that request, instead of immediately surfacing up an error to the GW/FE.
Note: I'm aware that this is a bit of a heavy hammer. We can discuss
about whether or not this is the right thing to do.
This would most likely also need to be accompanied with longer styx request timeouts; under the current default scheme, we'll end up waiting 15s before erroring out.
Alternatively, we could decrease the default timeout, and retry quicker.
=> GLOB-37084 Add automatic retries on failures

src/index.js, src/modules/__tests__/pagingBody.test.js, src/modules/index.js, src/modules/paging/all.js, src/modules/paging/index.js
Enabling pagination of search requests that expect parameters as body
For example:
```
GET https://service.env.globality.io/api/resource/batch
Content-Type: application/json; charset=UTF-8
{
"identifiers": ["ID1", "ID2"... "ID1000"],
"limit": 20,
"offset": 0
}
```
As opposed to:
```
GET https://service.env.globality.io/api/resource?identifiers=['ID1','ID2',...'ID9000']&limit=20&offset=0
```
A typical use case is to batch requests that take a long list of identifiers as a parameter
In this case searching via URL query is not possible because of URL length limit, resulting is 414 URI too long error
Currently `all()` paging function only supports search request that expect pagination parameters in URL query (as in the second example above)
Adding a new function  `allForBodySearchRequest()` …
=> enable pagination for body requests

.circleci/config.yml, src/__tests__/naming.test.js, src/clients/openapi.js, src/naming.js
To support Java based read service which uses camel case naming convention, we need to introduce new configuration set at the service level to override the default naming convention.
Sample configuration:
STYX__CLIENTS__READSERVICE__NAMING_OVERRIDE=true STYX__CLIENTS__READSERVICE__NAMING_PATH=preserveParameterName
STYX__CLIENTS__READSERVICE__NAMING_QUERY=preserveParameterName
=> GLOB-49581: Added configuration to override parameter naming

package.json, src/modules/__tests__/paging.test.js, src/modules/paging/all.js
**What?**
add warning log when large dataset returned with default page_size
**Why?**
To help find cases where we are fetching large sets of data in small increments.
=> Add validation warning to paging.all

.circleci/config.yml, src/clients/README.md, src/clients/openapi.js
https://globality.atlassian.net/browse/GLOB-51977
Seems to do what we want - passes the jwt through with any request provided it's in the request locals.
I will, of course, revert the circle config changes - I needed them so I could prepare a styx branch using this version of nodule-openapi to deploy to an environment (so I could be sure the JWT wasn't coming through in any logs).
I haven't managed to assert whether or not it'll get logged in sentry (working on this now)
It's not showing up in logs.
=> [GLOB-51977] Pass the JWT along with request headers in Open API Client

src/clients/openapi.js
Adding a warning to notify developer if a base url isn't present for one of the defined openapi clients
=> feat(GLOB-52415) warn if openapi client base url missing

src/__tests__/error.test.js, src/error.js
We recently discovered we are leaking auth headers to Loggly.
Currently, the surface area of this is still fairly small, but
obviously not ideal. An ideal infosec turnaround would be <48 hours
to fix this - which is why we are opting to prune auth headers from
the error headers attribute.
In the longer term, we would like to look at re-architecting
nodule-logging, but currently the library is untested and the risk of
contagion from making a risky change in that library is HIGH.
So, in this commit, we make sure to look for both Authorization and
authorization keys in the headers object, and if we find them, we use
lodash's omit() function (chosen because it preserves the original
headers object) to remove them.
=> Prune Auth Headers from OpenAPIError Object

package.json, src/__tests__/request.test.js, src/clients/__tests__/openapi.test.js, src/operation.js, src/request.js
As requested on [GLOB-61753] we want, by default, retry 501 and 503 errors reported by HAProxy. 
PR enabling proxy retries on Styx: https://github.com/globality-corp/ansible-deploy/pull/4003
[GLOB-61753]: https://globality.atlassian.net/browse/GLOB-61753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Retry proxy errors by default

package.json, src/clients/openapi.js, src/operation.js
Move logging to the operation level and consolidate with retry logs,
with the overall success (or not) of the operation headlining.
Retry information is included as structured properties of the log line.
This makes it easier to find requests that ended in end-client failure
while still allowing analysis of whether retry configuration is needed
or succesful.
=> Consolidate logs at the operation level

src/__tests__/openApiCodeGenClients/utils.test.js, src/openApiCodeGenClients/utils.js
Need to update the openapi nodule adapter to deal with camelCase operationIds.
We had originally assumed that operationIds would only be `snake_case`.
Have updated the implementation to deal with both cases and add extra test coverage.
=> Adding camelCase fix for operation name

src/__tests__/example.json, src/__tests__/openapi.test.js, src/operation.js
OpenAPI client provided by `nodule-openapi` is unable to properly handle empty response from successful `delete` operation. Currently, it treats such response as error and tries to parse it, so this error is raised:
```
OpenAPIError: null
63 |     const headers = req && req.getHeaders ? req.getHeaders() : null;
64 | 
> 65 |     return new OpenAPIError(message, code, data, headers);
|            ^
66 | }
67 | 
68 | 
at normalizeError (src/error.js:65:12)
```
Closes https://globality.atlassian.net/browse/GLOB-75641
- Reworked condition checking if there's success response to treat as success everything except `undefined`
- Added unit test
=> GLOB-75641: Fix improper handling of empty data

.bumpversion.cfg, package.json
Bump version after merging: https://github.com/globality-corp/nodule-openapi/pull/95
=> Bump version to 0.26.0

.bumpversion.cfg, package.json, src/__tests__/operation.test.js, src/clients/README.md, src/clients/__tests__/openapi.test.js, src/clients/openapi.js, src/modules/__tests__/paging.test.js, src/modules/__tests__/pagingBody.test.js, src/modules/paging/all.js, src/modules/paging/any.js, src/modules/paging/first.js, src/modules/paging/none.js, src/modules/paging/one.js, src/openApiCodeGenClients/__test__/helpers.test.js, src/openApiCodeGenClients/__test__/operation.test.js, src/openApiCodeGenClients/helpers.js, src/openApiCodeGenClients/operation.js, src/operation.js
We want to start populating X-Request-Client onto request headers.
Note that we only populate if we find the `user.clientId` field.
Also adds support to specifically set request headers if required.
=> [GLOB-75773] Adding support for client header + passing in additional request headers explicitly

.bumpversion.cfg, package.json, src/clients/README.md, src/clients/__tests__/openapi.test.js, src/clients/openapi.js, src/openApiCodeGenClients/__test__/operation.test.js
Why?
`X-Request-Client` shouldn't rely on local user, cause it may have different sources.
What?
Switched how the `X-Request-Client` is set.
=> Adjust source of X-Request-Client

package.json, yarn.lock
To address the security vulnerabilities reported by [Snyk](https://app.snyk.io/org/globality/projects?groupBy=targets&before&after&searchQuery=nodule-openapi).
Updated a number of dependencies that were highlighted as containing security vulnerabilities.
- axios
- @globality/nodule-config -> xml2js
=> fix: Update dependencies to fix security vulnerabilities

package.json, src/clients/openapi.js
Removing the warning around base clients not set. Added here -> https://github.com/globality-corp/nodule-openapi/pull/70/files
This causes so much spam in the test logs that it makes it completely useless as a warning.
=> reverting changes around warnings if no base url set

package.json, src/index.js, src/testing/index.js, src/testing/openapi.js
I'm looking into migrating capote to vitest since it has native support for TypeScript and ES6 modules.
The only problem is that we use `mockResponse` a lot and this repo uses jest under the hood, so we need another `mockResponse` and `mockError` that uses vitest instead.
=> Vitest support
